on: [push]

jobs:
  update_app_settings_job:
    runs-on: ubuntu-latest
    name: Create resources for an Azure Function App
    steps:
      - uses: actions/checkout@v1
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Create the Azure Function app resources
        id: create-function-app
        uses: shutchings/create-function-app@master
        with:
          configuration: ${{ secrets.AZURE_CONFIGURATION }}